<?php
/**
 * Created by PhpStorm.
 * User: tanzhenxing
 * Date: 2018/5/22
 * Time: 9:55
 */
namespace app\base\controller;

use app\common\controller\TemplatePath;
use app\common\model\Sysconfig;
use app\common\controller\Domain;
use app\site\model\Site;
use think\Controller;

class Base extends Controller
{
    protected $template_path;
    protected $site_config;
    protected $resource_path;
    protected $site_id;

    /**
     * 模块公用基本类
     * @throws \think\exception\DbException
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        // 获取当前模板路径
        $template = new TemplatePath();
        $template_path = $template->info();
        $template_path = strtolower($template_path);
        $this->template_path = $template_path;

        // 当前网站信息
        $domain = new Domain();
        $my_domain = $domain->info();
        $site = Site::get(['domain'=>$my_domain]);
        if(empty($site)){
            return '域名：' . $my_domain .  '未绑定！';
        }
        $this->assign('site',$site);
        $this->site_id = $site['id'];

        // 获取当前网站配置信息
        $site_data = Sysconfig::all();
        $site_config = array();
        foreach ($site_data as $item){
            $site_config[$item['varname']] = $item['value'];
        }
        $this->site_config = $site_config;
        $this->assign('site_config',$site_config);

        // 资源文件路径
        $template_data = Sysconfig::get(['varname'=>'cfg_df_style']);
        $template_name = $template_data['value'];
        $resource_path = '/resource/' . $template_name;
        $this->resource_path = $resource_path;
        $this->assign('resource_path',$resource_path);

    }
}